export const Types = {
    LOGIN: 'LOGIN',
    GET_USER_AUTH_TOKENS: 'GET_USER_AUTH_TOKENS',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
    FORM_SUBMITION_STATUS: 'FORM_SUBMITION_STATUS'
}
